import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-catastrophe-reinsurance-recoverable-management",
  "engine": "recovery",
  "title": "Catastrophe Reinsurance Recoverable Management",
  "shortTitle": "Catastrophe Reinsurance Recoverable Management",
  "tagline": "Accelerate catastrophe recoveries by allocating event losses through treaty towers and governing notices, proofs, and collections.",
  "industry": "Catastrophe Finance",
  "buyer": "Property insurers and reinsurance teams",
  "uiPort": 4663,
  "apiPort": 5663,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "Catastrophe Reinsurance Recoverable Management converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect catastrophe events, claims, loss estimates, occurrence definitions, hours clauses, retentions, limits, reinstatements, notices, bordereaux, collections, and cash in one accountable workflow. Accelerate catastrophe recoveries by allocating event losses through treaty towers and governing notices, proofs, and collections.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Catastrophe Reinsurance Recoverable Management evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("catastrophe-event-registry","CRR01","Catastrophe event registry","Execute catastrophe event registry using catastrophe events, claims, loss estimates, occurrence definitions, hours clauses, retentions, limits, reinstatements, notices, bordereaux, collections, and cash.","Produce a governed catastrophe event registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Catastrophe / Treaty Tower","text","Catastrophe / Treaty Tower · Standard Case"],["caseReference","Catastrophe event registry Reference","text","CRR01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",782500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",946825],["domainDriver","Treaty Layer","select","Per occurrence",["Per occurrence","Aggregate","Catastrophe excess"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Catastrophe event registry case","Claim loss ingestion case","Occurrence definition analysis case","Hours-clause grouping case","Ultimate loss estimate case"]}),
feature("claim-loss-ingestion","CRR02","Claim loss ingestion","Execute claim loss ingestion using catastrophe events, claims, loss estimates, occurrence definitions, hours clauses, retentions, limits, reinstatements, notices, bordereaux, collections, and cash.","Produce a governed claim loss ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Catastrophe / Treaty Tower","text","Catastrophe / Treaty Tower · Standard Case"],["caseReference","Claim loss ingestion Reference","text","CRR02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",782500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",946825],["domainDriver","Treaty Layer","select","Per occurrence",["Per occurrence","Aggregate","Catastrophe excess"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Catastrophe event registry case","Claim loss ingestion case","Occurrence definition analysis case","Hours-clause grouping case","Ultimate loss estimate case"]}),
feature("occurrence-definition-analysis","CRR03","Occurrence definition analysis","Execute occurrence definition analysis using catastrophe events, claims, loss estimates, occurrence definitions, hours clauses, retentions, limits, reinstatements, notices, bordereaux, collections, and cash.","Produce a governed occurrence definition analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Catastrophe / Treaty Tower","text","Catastrophe / Treaty Tower · Standard Case"],["caseReference","Occurrence definition analysis Reference","text","CRR03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",782500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",946825],["domainDriver","Treaty Layer","select","Per occurrence",["Per occurrence","Aggregate","Catastrophe excess"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Catastrophe event registry case","Claim loss ingestion case","Occurrence definition analysis case","Hours-clause grouping case","Ultimate loss estimate case"]}),
feature("hours-clause-grouping","CRR04","Hours-clause grouping","Execute hours-clause grouping using catastrophe events, claims, loss estimates, occurrence definitions, hours clauses, retentions, limits, reinstatements, notices, bordereaux, collections, and cash.","Produce a governed hours-clause grouping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Catastrophe / Treaty Tower","text","Catastrophe / Treaty Tower · Standard Case"],["caseReference","Hours-clause grouping Reference","text","CRR04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",782500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",946825],["domainDriver","Treaty Layer","select","Per occurrence",["Per occurrence","Aggregate","Catastrophe excess"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Catastrophe event registry case","Claim loss ingestion case","Occurrence definition analysis case","Hours-clause grouping case","Ultimate loss estimate case"]}),
feature("ultimate-loss-estimate","CRR05","Ultimate loss estimate","Execute ultimate loss estimate using catastrophe events, claims, loss estimates, occurrence definitions, hours clauses, retentions, limits, reinstatements, notices, bordereaux, collections, and cash.","Produce a governed ultimate loss estimate decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Catastrophe / Treaty Tower","text","Catastrophe / Treaty Tower · Standard Case"],["caseReference","Ultimate loss estimate Reference","text","CRR05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",782500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",946825],["domainDriver","Treaty Layer","select","Per occurrence",["Per occurrence","Aggregate","Catastrophe excess"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Catastrophe event registry case","Claim loss ingestion case","Occurrence definition analysis case","Hours-clause grouping case","Ultimate loss estimate case"]}),
feature("retention-erosion","CRR06","Retention erosion","Execute retention erosion using catastrophe events, claims, loss estimates, occurrence definitions, hours clauses, retentions, limits, reinstatements, notices, bordereaux, collections, and cash.","Produce a governed retention erosion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Catastrophe / Treaty Tower","text","Catastrophe / Treaty Tower · Standard Case"],["caseReference","Retention erosion Reference","text","CRR06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",782500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",946825],["domainDriver","Treaty Layer","select","Per occurrence",["Per occurrence","Aggregate","Catastrophe excess"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Catastrophe event registry case","Claim loss ingestion case","Occurrence definition analysis case","Hours-clause grouping case","Ultimate loss estimate case"]}),
feature("layer-allocation","CRR07","Layer allocation","Execute layer allocation using catastrophe events, claims, loss estimates, occurrence definitions, hours clauses, retentions, limits, reinstatements, notices, bordereaux, collections, and cash.","Produce a governed layer allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Catastrophe / Treaty Tower","text","Catastrophe / Treaty Tower · Standard Case"],["caseReference","Layer allocation Reference","text","CRR07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",782500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",946825],["domainDriver","Treaty Layer","select","Per occurrence",["Per occurrence","Aggregate","Catastrophe excess"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Catastrophe event registry case","Claim loss ingestion case","Occurrence definition analysis case","Hours-clause grouping case","Ultimate loss estimate case"]}),
feature("limit-exhaustion","CRR08","Limit exhaustion","Execute limit exhaustion using catastrophe events, claims, loss estimates, occurrence definitions, hours clauses, retentions, limits, reinstatements, notices, bordereaux, collections, and cash.","Produce a governed limit exhaustion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Catastrophe / Treaty Tower","text","Catastrophe / Treaty Tower · Standard Case"],["caseReference","Limit exhaustion Reference","text","CRR08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",782500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",946825],["domainDriver","Treaty Layer","select","Per occurrence",["Per occurrence","Aggregate","Catastrophe excess"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Catastrophe event registry case","Claim loss ingestion case","Occurrence definition analysis case","Hours-clause grouping case","Ultimate loss estimate case"]}),
feature("reinstatement-premium","CRR09","Reinstatement premium","Execute reinstatement premium using catastrophe events, claims, loss estimates, occurrence definitions, hours clauses, retentions, limits, reinstatements, notices, bordereaux, collections, and cash.","Produce a governed reinstatement premium decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Catastrophe / Treaty Tower","text","Catastrophe / Treaty Tower · Standard Case"],["caseReference","Reinstatement premium Reference","text","CRR09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",782500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",946825],["domainDriver","Treaty Layer","select","Per occurrence",["Per occurrence","Aggregate","Catastrophe excess"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Catastrophe event registry case","Claim loss ingestion case","Occurrence definition analysis case","Hours-clause grouping case","Ultimate loss estimate case"]}),
feature("cash-call-calculation","CRR10","Cash call calculation","Execute cash call calculation using catastrophe events, claims, loss estimates, occurrence definitions, hours clauses, retentions, limits, reinstatements, notices, bordereaux, collections, and cash.","Produce a governed cash call calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Catastrophe / Treaty Tower","text","Catastrophe / Treaty Tower · Standard Case"],["caseReference","Cash call calculation Reference","text","CRR10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",782500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",946825],["domainDriver","Treaty Layer","select","Per occurrence",["Per occurrence","Aggregate","Catastrophe excess"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Catastrophe event registry case","Claim loss ingestion case","Occurrence definition analysis case","Hours-clause grouping case","Ultimate loss estimate case"]}),
feature("notice-deadline-control","CRR11","Notice deadline control","Execute notice deadline control using catastrophe events, claims, loss estimates, occurrence definitions, hours clauses, retentions, limits, reinstatements, notices, bordereaux, collections, and cash.","Produce a governed notice deadline control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Catastrophe / Treaty Tower","text","Catastrophe / Treaty Tower · Standard Case"],["caseReference","Notice deadline control Reference","text","CRR11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",782500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",946825],["domainDriver","Treaty Layer","select","Per occurrence",["Per occurrence","Aggregate","Catastrophe excess"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Catastrophe event registry case","Claim loss ingestion case","Occurrence definition analysis case","Hours-clause grouping case","Ultimate loss estimate case"]}),
feature("proof-of-loss-package","CRR12","Proof-of-loss package","Execute proof-of-loss package using catastrophe events, claims, loss estimates, occurrence definitions, hours clauses, retentions, limits, reinstatements, notices, bordereaux, collections, and cash.","Produce a governed proof-of-loss package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Catastrophe / Treaty Tower","text","Catastrophe / Treaty Tower · Standard Case"],["caseReference","Proof-of-loss package Reference","text","CRR12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",782500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",946825],["domainDriver","Treaty Layer","select","Per occurrence",["Per occurrence","Aggregate","Catastrophe excess"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Catastrophe event registry case","Claim loss ingestion case","Occurrence definition analysis case","Hours-clause grouping case","Ultimate loss estimate case"]}),
feature("reinsurer-query-workflow","CRR13","Reinsurer query workflow","Execute reinsurer query workflow using catastrophe events, claims, loss estimates, occurrence definitions, hours clauses, retentions, limits, reinstatements, notices, bordereaux, collections, and cash.","Produce a governed reinsurer query workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Catastrophe / Treaty Tower","text","Catastrophe / Treaty Tower · Standard Case"],["caseReference","Reinsurer query workflow Reference","text","CRR13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",782500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",946825],["domainDriver","Treaty Layer","select","Per occurrence",["Per occurrence","Aggregate","Catastrophe excess"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Catastrophe event registry case","Claim loss ingestion case","Occurrence definition analysis case","Hours-clause grouping case","Ultimate loss estimate case"]}),
feature("collection-reconciliation","CRR14","Collection reconciliation","Execute collection reconciliation using catastrophe events, claims, loss estimates, occurrence definitions, hours clauses, retentions, limits, reinstatements, notices, bordereaux, collections, and cash.","Produce a governed collection reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Catastrophe / Treaty Tower","text","Catastrophe / Treaty Tower · Standard Case"],["caseReference","Collection reconciliation Reference","text","CRR14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",782500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",946825],["domainDriver","Treaty Layer","select","Per occurrence",["Per occurrence","Aggregate","Catastrophe excess"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Catastrophe event registry case","Claim loss ingestion case","Occurrence definition analysis case","Hours-clause grouping case","Ultimate loss estimate case"]}),
feature("event-tower-analytics","CRR15","Event tower analytics","Execute event tower analytics using catastrophe events, claims, loss estimates, occurrence definitions, hours clauses, retentions, limits, reinstatements, notices, bordereaux, collections, and cash.","Produce a governed event tower analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Catastrophe / Treaty Tower","text","Catastrophe / Treaty Tower · Standard Case"],["caseReference","Event tower analytics Reference","text","CRR15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",782500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",946825],["domainDriver","Treaty Layer","select","Per occurrence",["Per occurrence","Aggregate","Catastrophe excess"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Catastrophe event registry case","Claim loss ingestion case","Occurrence definition analysis case","Hours-clause grouping case","Ultimate loss estimate case"]})
]);
